### ISSUE TITLE
How get the status of the valve ?

### ISSUE THREAD

**Issue by minscof** [RoyOltmans/aqualin-mqtt-deamon#1]
First, I want to thank you for this project and tell you that it works perfectly.

Nevertheless, I have a question : how can I get the status of the valve : on or off ? Is it a way to query the valve and can you document it ?

Thank you

**Comment by RoyOltmans** [comment]
I have a new version in the works with status responses, will upload that version somewhere coming weeks. It will also be more compatible with HA. Problem is I converged the whole setup with Myflora. Will have a look if I can split both projects.

**Comment by minscof** [comment]
Thanks for your answer : I m waiting news from you but sommer is coming

**Comment by minscof** [comment]
Summer is coming, is your new version  almost ready ?

**Comment by minscof** [comment]
up, can you give information about the new version ?

**Comment by DAN-GITHUB-ACCESS** [comment]
Hi, thank you for this project. How about the new version ?
Thx........

**Comment by RoyOltmans** [comment]
Wrote the feature, hope it works for you :)
