### ISSUE TITLE
MQTT 

### ISSUE THREAD

**Issue by schmeckm** [RoyOltmans/aqualin-mqtt-deamon#2]
Dear All,
I tried to execute the following command on my rasberryPi and get the following error.
./aqualin-mqtt-deamon.py
MQTT: Connected with result code 0
the screen is afterwards hanging and I can not continue with the other steps.

**Comment by RoyOltmans** [comment]
Next call elaborates on this call. I am closing this one and continuing on the next. https://github.com/RoyOltmans/aqualin-mqtt-deamon/issues/3

**Comment by schmeckm** [comment]
Hi Roy

Many Thanks. You are amazing. Awesome it works. I can fire Event and the Aqualin receive the message and react accordingly. 

It was the MAC Address. As you said the address was wrong.

right I can only sent off and on. 

If fire Events like this:

mosquitto_pub -h 192.168.178.26 -t home/aqualin/01:02:03:04:05:08/status/on -m 1

Regards,  MArkus

**Comment by schmeckm** [comment]
My last question is… Im using a Raspberry 3. 

I assume to make the robust more robust in case of a server interruption to eventually restart the Rasp. 

Does it mean that it would be better to put the following script into autostart?

./aqualin-mqtt-deamon.py
and

mosquitto_sub -h [MQTT Host] -t '#' -v
THX

Markus

**Comment by RoyOltmans** [comment]
So firstly be carefull with the commands if you use payload -m 1 it will be open for one minute (limitation of the internal commands of the Aqualin). I use a broad timer of 30min and shut it down with the off command.

Secondly you can add the python script as an service to Raspbian. 

You can do this by adding a file in /etc/systemd/system/

call the file for example mqttaqualin.service

The content of the file would be in the line of the following:

[Unit]
Description=Aqualin MQTT service
After=network.target

[Service]
ExecStart=/usr/bin/python -u aqualin-mqtt-deamon.py
WorkingDirectory=/opt/aqualin-mqtt-deamon/
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root

[Install]
WantedBy=multi-user.target

For details see: https://www.raspberrypi.org/documentation/linux/usage/systemd.md

This way you won't ever need to restart, start the service (and it will run on the background)

Hope this helps!
